### ISSUE TITLE
Error Unmarshaling from sqlx queries

### ISSUE THREAD

**Issue by pragmaticivan** [oklog/ulid#77] opened 2022-03-24 13:49 UTC
```
type Team struct {
	ID         ulid.ULID `db:"id"`
	Name       string    `db:"name"`
	Status     string    `db:"status"`
	CreatedAt  time.Time `db:"created_at"`
	UpdatedAt  time.Time `db:"updated_at"`
	Archivedat time.Time `db:"archived_at"`
}
```

Usage:
```
	query := "SELECT * FROM teams WHERE status = 'active'"
	teams := []Team{}
	if err := r.DbConn.SelectContext(ctx, &teams, query); err != nil {
		return nil, errors.Wrap(err, "selecting teams")
	}
```

Result:
`error retrieving data selecting teams: sql: Scan error on column index 0, name "id": ulid: bad data size when unmarshaling`

Table Structure:
```
create table teams (
        id varchar(26) not null,
        name varchar(255) not null,
        status varchar(26) not null,
        created_at datetime not null default now(),
        updated_at datetime not null default now(),
        archived_at datetime null
      ) default character set utf8mb4 engine = InnoDB;
```

**Comment by pragmaticivan** [comment] 2022-03-24 13:57
I'm assuming it would need something like https://github.com/google/uuid/blob/master/sql.go

**Comment by peterbourgon** [comment] 2022-03-24 22:42
[ULIDs are 16 bytes](https://pkg.go.dev/github.com/oklog/ulid/v2#ULID). Does changing `varchar(26)` to `varchar(16)` fix it?

**Comment by pragmaticivan** [comment] 2022-03-25 13:12
`Canonically encoded as a 26 character string, as opposed to the 36 character UUID`

ex: https://ulidgenerator.com/

**Comment by peterbourgon** [comment] 2022-03-25 13:38
Yes, that's the Crockford base 32 encoding, which indeed occupies 26 characters. But `ulid.ULID` is 16 bytes in memory, and the default [Value](https://pkg.go.dev/github.com/oklog/ulid#ULID.Value) will send those raw 16 bytes by default. Take a look at the docs for that method and also [Scan](https://pkg.go.dev/github.com/oklog/ulid#ULID.Scan), and maybe check that the data in the column is actually 26 characters, and that your DB driver is providing a string type to the Scan method.

**Comment by pragmaticivan** [comment] 2022-03-25 16:32
I'm assuming it has to do with that block https://github.com/oklog/ulid/blob/master/ulid.go#L504-L506

**Comment by peterbourgon** [comment] 2022-03-25 16:48
Maybe. Quoting the documentation...

> Value . . . returns the value represented as a byte slice. If instead a string is desirable, a wrapper type can be created that calls String().

If you do that, does it behave as you expect?

**Comment by pragmaticivan** [comment] 2022-03-25 18:00
Only changing the Value implementation here might not do much. I actually think because it's implementing the SQL module it should follow the same approach used for google UUID https://github.com/google/uuid/blob/master/sql.go#L57-L59

```
func (id ULID) Value() (driver.Value, error) {
	return id.MarshalText()
}
```

As this one is only for databases.

**Comment by peterbourgon** [comment] 2022-03-25 18:07
Try it and report back.

Just to be explicit: ULIDs (and UUIDs!) have string _representations_, and Crockford base 32 happens to be the canonical one, but they aren't actually strings. They are actually 16 raw bytes, as specified in [the spec](https://github.com/oklog/ulid#binary-layout-and-byte-order). You can of course decide to make a DB table that has a ULID column defined as varchar(26) and expecting the canonical string encoding. But — I hope! — you can just as easily define that column as 16 raw bytes, which would be both more efficient and more correct.

**Comment by pragmaticivan** [comment] 2022-03-25 18:35
Will try that out with bytes, although I actually did try with only Value with a custom type for ULID and that required also implementing MarshalTex, etc... as it does not use generics.

Ex where it also supports string: https://github.com/segmentio/ksuid/blob/master/ksuid.go#L139-L160

Context: https://github.com/segmentio/ksuid#plays-well-with-others

**Comment by pragmaticivan** [comment] 2022-03-25 19:14
For some reason it works if I comment that verification:

```
func (id *ulid.ULID) UnmarshalBinary(data []byte) error {

	// if len(data) != len(*id) {
	// 	return ErrDataSize
	// }

	copy((*id)[:], data)
	return nil
}
```

The part I didn't get is the result of Db as a list of bytes instead of a string. Which does not match 16, but 26 instead.

**Comment by peterbourgon** [comment] 2022-03-25 20:11
If something is calling `UnmarshalBinary` with `len(data) == 26`, then that indicates the `data` is a string representation of the ULID, not the actual bytes. If that's true, then `copy((*id)[:], data)` is going to set `id` to an incorrect value.

But `UnmarshalBinary` is [only called](https://github.com/oklog/ulid/blob/v1.3.1/ulid.go#L449) when `Scan` receives a `[]byte` from the DB driver. So it looks like something in your stack, or maybe many things, are pretty confused at the moment.

**Comment by pragmaticivan** [comment] 2022-03-25 20:13
> If something is calling `UnmarshalBinary` with `len(data) == 26`, then that indicates the `data` is a string representation of the ULID, not the actual bytes. If that's true, then `copy((*id)[:], data)` is going to set `id` to an incorrect value.
> 
> But `UnmarshalBinary` is [only called](https://github.com/oklog/ulid/blob/v1.3.1/ulid.go#L449) when `Scan` receives a `[]byte` from the DB driver. So it looks like something in your stack, or maybe many things, are pretty confused at the moment.

yeah, I think SQL driver does that with binary. Worth investigating a bit more when I have more time, but I've tested the same code with 4 different generators and the behavior was similar. That check was not in there though.

**Comment by peterbourgon** [comment] 2022-03-25 20:50
> yeah, I think SQL driver does that with binary

In theory the driver should provide `Scan` with a value whose type corresponds to the column in the DB. `varchar(26)` should I guess be a `string`! What driver do you use? Do you have a reproducer?

**Comment by pragmaticivan** [comment] 2022-03-25 20:54
> > yeah, I think SQL driver does that with binary
> 
> In theory the driver should provide `Scan` with a value whose type corresponds to the column in the DB. `varchar(26)` should I guess be a `string`! What driver do you use? Do you have a reproducer?

"github.com/go-sql-driver/mysql"
"github.com/jmoiron/sqlx"

I will try to build a POC to reproduce the problem later.

**Comment by pragmaticivan** [comment] 2022-03-25 21:01
```go
//go:embed certs/us-east-1-bundle.pem
var awsCaBundle string

// NewDatabaseConnection -
func NewDatabaseConnection(config config.AppConfig) (*sqlx.DB, error) {
	rootCertPool := x509.NewCertPool()
	if ok := rootCertPool.AppendCertsFromPEM([]byte(awsCaBundle)); !ok {
		return nil, errors.New("failed to append PEM")
	}
	mysql.RegisterTLSConfig("custom", &tls.Config{
		RootCAs: rootCertPool,
	})

	tls := "?parseTime=true"

	if config.Application.AppEnv != "local" {
		tls = tls + "&tls=custom"
	}

	// Configure DB
	connection := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s%s", config.Db.Username, config.Db.Password, config.Db.Host, config.Db.Port, config.Db.DatabaseName, tls)

	dbConn, err := sqlx.Connect("mysql", connection)

	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
		return nil, err
	}

	return dbConn, nil
}
```

```go
package team

import (
	"context"

	"github.com/jmoiron/sqlx"
	"github.com/pkg/errors"
)

// Repository -
type Repository struct {
	DbConn *sqlx.DB
}

// NewTeamRepository -
func NewTeamRepository(dbConn *sqlx.DB) Repository {
	return Repository{
		DbConn: dbConn,
	}
}

// FindAll -
func (r Repository) FindAll(ctx context.Context) ([]Team, error) {
	query := "SELECT * FROM teams WHERE status = 'active'"
	teams := []Team{}
	if err := r.DbConn.SelectContext(ctx, &teams, query); err != nil {
		return nil, errors.Wrap(err, "selecting teams")
	}
	return teams, nil
}

```

**Comment by pragmaticivan** [comment] 2022-03-25 21:07
Something tells me something of the sorts would be needed here: https://github.com/segmentio/ksuid/blob/7e86c6a662671a7b81379d16a8a240f9fbcfe058/ksuid.go#L162-L174

**Comment by peterbourgon** [comment] 2022-03-25 21:11
Play around with wrapper types, as described in the docs for the Value method, and see what you can discover. I can say that deciding which type to decode into based on the length of the received value is too fragile to be considered a viable solution.

**Comment by peterbourgon** [comment] 2022-03-26 20:06
Closing for now.

**Closed by peterbourgon** 2022-03-26 20:06 UTC

**Comment by pragmaticivan** [comment] 2022-03-26 22:46
The wrapper types require rewriting more methods. If this lib has some code for `database/sql/driver` it might be worth validating the problem with tests before closing the issue. There are plenty of examples already to validate that it's not behaving as expected. 

ref: https://github.com/oklog/ulid/blob/master/ulid.go#L19

**Comment by peterbourgon** [comment] 2022-03-28 20:12
> There are plenty of examples already to validate that it's not behaving as expected.

If you can give me a repro case, I'm happy to investigate, but AFAICT so far everything is behaving as expected.
